services:
  - type: web
    name: covid-detection
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app/app_complete.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
